name: build-and-push
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/753698311885/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-service-account@nitraai.iam.gserviceaccount.com"

      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            docker-hub-token:nitraai/docker-hub

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: vitaliytv
          password: ${{ steps.secrets.outputs.docker-hub-token }}

      - uses: actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: build and push
        run: |
          docker buildx build . \
          --progress=plain \
          --platform linux/amd64,linux/arm64 \
          --tag nitra/mssql-server:latest \
          --push
